### ISSUE TITLE
dataset for training

### ISSUE THREAD

**Issue by AsserOssama** [yyang181/NTIRE23-VIDEO-COLORIZATION#1]
could u tell how to train the deep exemplar-based video colorization and the format of the dataset to train the model?

**Comment by yyang181** [comment]
Hi, sorry for the delayed response. Please check https://github.com/zhangmozhe/Deep-Exemplar-based-Video-Colorization/issues/12#issuecomment-1963411048. 

Kindly reach out should you have any additional detailed inquiries.
