### ISSUE TITLE
model weight URL link for BISTNet 

### ISSUE THREAD

**Issue by dolphin0104** [yyang181/NTIRE23-VIDEO-COLORIZATION#13]
Hello, the model weight URL link for BISTNet is returning a 404 error and cannot be accessed. Could you provide an alternative way to download the weights?

**Comment by yyang181** [comment]
Hi, the URL (https://github.com/yyang181/NTIRE23-VIDEO-COLORIZATION/releases/download/v1.0.3/checkpoints.zip ) has been updated, please try again.
