### ISSUE TITLE
LICENCE

### ISSUE THREAD

**Issue by milmor** [yyang181/NTIRE23-VIDEO-COLORIZATION#3]
Fantastic work, but, the whole project is MIT Licence?

MIT License

Copyright (c) 2020 zhangmozhe

It seems that RAFT code is under BSD 3-Clause License and pytorch-hed is under GNU GENERAL PUBLIC LICENSE.

**Comment by yyang181** [comment]
Thanks so much for bringing up this concern and for your interest in the project. We appreciate your attention to licensing details. 

We have updated the licensing details in both [README.md](https://github.com/yyang181/NTIRE23-VIDEO-COLORIZATION/blob/main/README.md) and [LICENSES.md](https://github.com/yyang181/NTIRE23-VIDEO-COLORIZATION/blob/main/BiSTNet-NTIRE2023/LICENSE.md). 

If you have any further questions or if there's anything else I can help you with, please feel free to let me know. I'm here to assist.
