### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv.cnn'

### ISSUE THREAD

**Issue by techhalloman** [yyang181/NTIRE23-VIDEO-COLORIZATION#4]
File "/home/sos/Documents/NTIRE23-VIDEO-COLORIZATION/BiSTNet-NTIRE2023/test_NTIRE23_Track_1_FID.py", line 18, in <module>
    from models.ColorVidNet import SPyNet
  File "/home/sos/Documents/NTIRE23-VIDEO-COLORIZATION/BiSTNet-NTIRE2023/models/ColorVidNet.py", line 6, in <module>
    from mmcv.cnn import ConvModule
ModuleNotFoundError: No module named 'mmcv.cnn'

**Comment by yyang181** [comment]
Hi, thanks so much for your interest in the project. 

The encountered challenge pertains to the mmcv version. Specifically, our project relies on [mmcv 1.x](https://github.com/open-mmlab/mmcv/tree/1.x/mmcv), whereas the default branch, denoted as [mmcv 2.x](https://github.com/open-mmlab/mmcv/tree/main/mmcv), proves incompatible.

Ensure that your mmcv version is set to 1.x, and verify your PyTorch version, avoiding the use of PyTorch 2.1.0, as outlined in this [issue](https://github.com/open-mmlab/mmcv/issues/2938). 

Additionally, please be informed that we intend to release our Colab demo in the coming days. 

Hope these information finds you well.

**Comment by yyang181** [comment]
Hi @TechHalloman, the colab demo has been released at https://colab.research.google.com/drive/1T7-BOpSkd41fNW8bffo6aXSeK_jizsvv#scrollTo=OVMNWEaz2b06.
