### ISSUE TITLE
colab not working

### ISSUE THREAD

**Issue by techhalloman** [yyang181/NTIRE23-VIDEO-COLORIZATION#5]
Colab demo for BiSTNet. not working stop pip installation.

**Comment by yyang181** [comment]
Hi @TechHalloman, if you are encountering pip installation errors that state Torch 2.0.0 is incompatible, it is generally safe to ignore them if they do not affect the running of this project. 

The errors are likely caused by torchdata and torchtext requiring torch version 2.0.1, which is the default version in Google Colab. However, this project specifically requires torch version other than 2.0.1 as discessed in #4. One option to resolve this issue is to uninstall torchdata and torchtext first using the following commands:
```!pip3 uninstall torch torchdata torchtext -y```

After uninstalling, you can proceed to install the pytorch versions required for this project and the errors should be gone:
```!pip3 install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1```

I updated the colab to address these errors, if there are further questions, please let me know.

**Comment by techhalloman** [comment]
![test](https://github.com/yyang181/NTIRE23-VIDEO-COLORIZATION/assets/33749742/456f09c0-4f93-4c41-8c73-eed1824f6e4a)

**Comment by techhalloman** [comment]
![test2](https://github.com/yyang181/NTIRE23-VIDEO-COLORIZATION/assets/33749742/1aa72865-0fcb-4441-9757-93dd0268c0df)

**Comment by yyang181** [comment]
Hello @TechHalloman, please ensure that you have followed the instructions below to clone the repository and navigate to the correct directory:
1. Execute the first command to clone the repository.
2. Execute the second command to change to the appropriate directory.

On the left-hand side, you will find a folder icon which you can click to access the desired location. Once there, you should be able to locate the file "pip_requirements.txt" as depicted in the provided image.
![2023-12-05_20-48](https://github.com/yyang181/NTIRE23-VIDEO-COLORIZATION/assets/38424900/50b5bf46-d815-44cb-b9a2-c085d3bb7ad5)

**Comment by yyang181** [comment]
> ![test2](https://private-user-images.githubusercontent.com/33749742/288044587-1aa72865-0fcb-4441-9757-93dd0268c0df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODEyNzMsIm5iZiI6MTcwMTc4MDk3MywicGF0aCI6Ii8zMzc0OTc0Mi8yODgwNDQ1ODctMWFhNzI4NjUtMGZjYi00NDQxLTk3NTctOTNkZDAyNjhjMGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDEyNTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NDAyM2RmNGU5NTRlN2RmYjJhZjU5ZGE0MjgwZmEwMjM0OTQwM2JhYjY5YTNiNzJlM2VhYmU1MmNmOTkyNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JcpVw_FNce892OPiPCzgeoboWH-opK1tU9Ux75Ax82k)

You can just ignore these errors, the demo would work with these errors.

**Comment by techhalloman** [comment]
3$ CUDA_VISIBLE_DEVICES=0 python test_NTIRE23_Track_1_FID.py
Traceback (most recent call last):
  File "/home/sos/Documents/NTIRE23-VIDEO-COLORIZATION/BiSTNet-NTIRE2023/test_NTIRE23_Track_1_FID.py", line 18, in <module>
    from models.ColorVidNet import SPyNet
  File "/home/sos/Documents/NTIRE23-VIDEO-COLORIZATION/BiSTNet-NTIRE2023/models/ColorVidNet.py", line 7, in <module>
    from mmcv.runner import load_checkpoint
ImportError: cannot import name 'load_checkpoint' from 'mmcv.runner' (unknown location)

**Comment by yyang181** [comment]
Please check your mmcv version (1.x should work). You can see that in https://github.com/open-mmlab/mmcv/blob/1.x/mmcv/runner/__init__.py L.6, these is a function named ```load_checkpoint```. 

Note that mmcv 1.x supports pytorch 1.5-1.13, see https://github.com/open-mmlab/mmcv/tree/1.x . 

A simple way to install mmcv 1.x is 
```pip3 install -U openmim```
```mim install mmcv-full```

To check your mmcv version:
```pip list | grep mmcv```

Correct print:
```mmcv-full 1.7.1```

**Comment by yyang181** [comment]
> 3$ CUDA_VISIBLE_DEVICES=0 python test_NTIRE23_Track_1_FID.py Traceback (most recent call last): File "/home/sos/Documents/NTIRE23-VIDEO-COLORIZATION/BiSTNet-NTIRE2023/test_NTIRE23_Track_1_FID.py", line 18, in from models.ColorVidNet import SPyNet File "/home/sos/Documents/NTIRE23-VIDEO-COLORIZATION/BiSTNet-NTIRE2023/models/ColorVidNet.py", line 7, in from mmcv.runner import load_checkpoint ImportError: cannot import name 'load_checkpoint' from 'mmcv.runner' (unknown location)

Please check your mmcv version (1.x should work). You can see that in https://github.com/open-mmlab/mmcv/blob/1.x/mmcv/runner/__init__.py L.6, these is a function named load_checkpoint.

Note that mmcv 1.x supports pytorch 1.5-1.13, see https://github.com/open-mmlab/mmcv/tree/1.x .

A simple way to install mmcv 1.x is
```pip3 install -U openmim```
```mim install mmcv-full```

To check your mmcv version:
```pip list | grep mmcv```

Correct output should be:
```mmcv-full 1.7.1```

**Comment by techhalloman** [comment]
mim install mmcv-full==1.7.0


got it
