### ISSUE TITLE
Train dataset preprocess issue

### ISSUE THREAD

**Issue by doolachen** [yyang181/NTIRE23-VIDEO-COLORIZATION#8]
Can you provide an example of a data structure for reading the **train_gt (colorize)** and **train (grayscale)** videos datasets downloaded from NTIRE? 

I would like to use [Deep-Exemplar-based-Video-Colorization](https://github.com/zhangmozhe/Deep-Exemplar-based-Video-Colorization) for training. 

It seems that I have not obtained any paradigm of data structure from VideosDataset_20230227_ntire23 and parse_images_20230227_ntire23. 

Again, for VideosDataset_ImageNet, it seems to read `pairs.txt `,`pairs_mid.txt `,`pairs_bad.txt `. How do I obtain these txt files？

Thank you for any valuable suggestions.

**Comment by yyang181** [comment]
Hi @doolachen, sorry for the late response. I am planning to add a new branch named 'DeepExemplar' to this repository to facilitate the training for the [Deep-Exemplar-based-Video-Colorization](https://github.com/zhangmozhe/Deep-Exemplar-based-Video-Colorization) project. This update should take a day or two to implement. Please stay tuned for further updates on our progress.

**Comment by doolachen** [comment]
> Hi @doolachen, sorry for the late response. I am planning to add a new branch named 'DeepExemplar' to this repository to facilitate the training for the [Deep-Exemplar-based-Video-Colorization](https://github.com/zhangmozhe/Deep-Exemplar-based-Video-Colorization) project. This update should take a day or two to implement. Please stay tuned for further updates on our progress.

Thank you for your reply, I'll pay attention to your progress. Looking forward to your further work.

**Comment by yyang181** [comment]
Hi @doolachen, the new banch DeepExemplar has beed added, please let me know if you have further questions.

**Comment by doolachen** [comment]
I have successfully started the training process after a short period of debugging.  Especially thank you for the help and code you provided, this is a great assistance to me! 
By the way, on line 351 of `utils/util_distortion.py`:
https://github.com/yyang181/NTIRE23-VIDEO-COLORIZATION/blob/7e87301742ac36228364fb758e6ace7e3a5b4b97/utils/util_distortion.py#L351 

`height_start` is not defined. I think it might be `height_crop_start`. This is just a minor issue and does not impact the training. 
Thanks again for your contribution to the [Deep-Exemplar-based Video Colorization](https://github.com/zhangmozhe/Deep-Exemplar-based-Video-Colorization)  project!

**Comment by doolachen** [comment]
> Hi @doolachen, the new banch DeepExemplar has beed added, please let me know if you have further questions.

There is an additional issue that I tried to load the trained model using test.py, but it seems that the parameters of the model do not match. However, there is no problem loading the pre-trained models provided by [Deep-Exemplar-based Video Colorization](https://github.com/zhangmozhe/Deep-Exemplar-based-Video-Colorization). Are the models loaded here the same?
