### ISSUE TITLE
Train script BiSTNet

### ISSUE THREAD

**Issue by roxanacincan** [yyang181/NTIRE23-VIDEO-COLORIZATION#9]
Hello,

Are there any plans for a release in the future of a train script for BiSTNet?

Thank you!

**Comment by yyang181** [comment]
We have released the training script for DeepExemplar in the "DeepExemplar" branch, as referenced in issue #8. This training script includes almost everything required to train our BiSTNet. We plan to release the official training script by July 2024. Stay tuned for further updates.
